function Form(props) {
  function submit(e) {
    e.preventDefault();

    // console.log(e.target.elements.task.value);
    props.addTask(e.target.elements.task.value);
    //completed: false, generated by app
    //task: from form
    //id: generated by app
  }

  return (
    <form onSubmit={submit}>
      <label htmlFor="form_task">Task</label>
      <input required type="text" name="task" id="form-task" />
      <button>add task</button>
    </form>
  );
}

export default Form;
